name: Package and Release Scripts

on:
  push:
    branches:
      - main  # Change to master or your primary branch if different
    paths:
      - 'Scripts/**'
      - '.github/workflows/main.yml'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Zip Archive
        run: |
          mkdir -p ParryIndicator/Scripts
          cp -r Scripts/. ParryIndicator/Scripts/
          cp enabled.txt ParryIndicator/
          zip -r ParryIndicatorMk2.zip ParryIndicator

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.2.${{ github.run_number }}
          name: Release ${{ steps.vars.outputs.tag_date }}
          draft: false
          prerelease: false
          files: ParryIndicatorMk2.zip
